# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='resource',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='codemarker.Resource'),
        ),
    ]
