# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0002_auto_20171108_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='assessment_id',
            new_name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='assessment_id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='codemarker.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='assessment',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='codemarker.Assessment'),
            preserve_default=False,
        ),
    ]
