# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0002_auto_20171109_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='additional_help',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
