# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 18:55
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0002_auto_20180204_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=django_mysql.models.EnumField(choices=[('python', 'python'), ('python3', 'python3'), ('java', 'java'), ('cpp', 'cpp'), ('ruby', 'ruby')], default='python'),
        ),
    ]
