# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0003_auto_20171108_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='assessment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='resources',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codemarker.Resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='assessments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codemarker.Assessment'),
        ),
    ]
