# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 23:06
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0004_auto_20180212_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=django_mysql.models.EnumField(choices=[('python2', 'python2'), ('python3', 'python3'), ('java', 'java'), ('cpp', 'cpp'), ('c', 'c'), ('ruby', 'ruby')], default='python2'),
        ),
    ]
