# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0004_auto_20171113_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
