# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0005_auto_20180212_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='info',
            field=models.TextField(default='None'),
        ),
    ]
