# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0005_auto_20171113_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='codemarker.Assessment'),
        ),
    ]
