# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0006_auto_20171108_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assessments',
            new_name='assessment',
        ),
    ]
