# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0006_auto_20171113_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='timeTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='codemarker.Assessment'),
        ),
    ]
