# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codemarker', '0008_auto_20180216_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ehehehee',
            field=models.CharField(default='OOKOK', max_length=400),
            preserve_default=False,
        ),
    ]
