# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codemarker', '0009_course_ehehehee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ehehehee',
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
