# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 19:55
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=django_mysql.models.EnumField(choices=[('python2', 'python2'), ('python3', 'python3'), (
                'java', 'java'), ('cpp', 'cpp'), ('ruby', 'ruby')], default='python2'),
        ),
    ]
