# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_submission_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesUsers',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app.Course')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
