# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_coursesusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesusers',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesusers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CoursesUsers',
        ),
    ]
