# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 18:58
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180221_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputgenerator',
            name='language',
            field=django_mysql.models.EnumField(choices=[('python2', 'python2'), ('python3', 'python3'), (
                'java', 'java'), ('cpp', 'cpp'), ('c', 'c'), ('ruby', 'ruby')], default='python2'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=django_mysql.models.EnumField(choices=[('python2', 'python2'), ('python3', 'python3'), (
                'java', 'java'), ('cpp', 'cpp'), ('c', 'c'), ('ruby', 'ruby')], default='python2'),
        ),
    ]
