# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180224_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputgenerator',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content_type',
        ),
    ]
