# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180227_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='data',
        ),
    ]
