# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_submission_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
