# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180227_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=django_mysql.models.EnumField(choices=[('start', 'start'), ('in_progress', 'in_progress'), ('complete', 'complete'), ('late', 'late')]),
        ),
    ]
