# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180227_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(validators=[rest_framework.compat.MinValueValidator(0), rest_framework.compat.MaxValueValidator(100)]),
        ),
    ]
