# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180228_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='dynamic_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='num_of_static',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='static_input',
            field=models.BooleanField(default=False),
        ),
    ]
