# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200124_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='max_time',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
