"""
Autogenerated module by Django.

@TeamAlpha 2018
CodeMarker
urls.py
"""

import django.conf.urls

from . import views

urlpatterns = [
    django.conf.urls.url(r'$', views.index, name='index'),
]
